### ISSUE TITLE
Support current logict version 

### ISSUE THREAD

**Issue by alaendle** [wrengr/unification-fd#70]
to be up-to-date with the ecosystem and in order to get the package back to stackage (see https://github.com/commercialhaskell/stackage/issues/6955).

https://hackage.haskell.org/package/logict-0.8.1.0/changelog

**Comment by roconnor-blockstream** [comment]
unification-fd is now broken in nixpkgs-unstable for the same reason.  Updating the upper bounds for logict seems to be all that is needed.

**Comment by wrengr** [comment]
fixed by 24d4279f85192d218ba81cff4af40172ffb564e1
